---
- name: Configurar máquina virtual para ejecutar contenedores con Podman
  hosts: vm_podman
  become: true

  tasks:
    - name: Actualizar caché de paquetes APT
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Instalar Podman
      ansible.builtin.apt:
        name: podman
        state: present

    - name: Instalar colección de herramientas útiles
      ansible.builtin.apt:
        name:
          - curl
          - jq
        state: present
