apiVersion: v1
kind: Pod
metadata:
  name: pod-prueba-acr
  labels:
    app: prueba-acr
spec:
  containers:
    - name: web-nginx
      image: cp2cristinaacr2026.azurecr.io/web-nginx:casopractico2
      ports:
        - containerPort: 443
  restartPolicy: Never
